### ISSUE TITLE
(L)GPL distribution available?

### ISSUE THREAD

**Issue by mabolek** [AlfonsoML/confighelper#29]
Hi!

At https://ckeditor.com/cke4/addon/confighelper this extension is listed as licensed under both GPL, LGPL, and MPL. This repository, however, is only MPL.

Is there an (L)GPL distribution available on github?

**Comment by AlfonsoML** [comment]
Ok, I've adjusted the listing at https://ckeditor.com/cke4/addon/confighelper  
Just MPL.
